# fly.toml app configuration file generated for wundergraph-service on 2023-11-16T16:49:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wundergraph-service"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 9991
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 9991
